brew "autojump"
brew "fzf"
brew "git"
brew "htop"
brew "make"
brew "neovim", args: ["HEAD"]
brew "tmux"
brew "zsh"
brew "tig"
brew "jq"
brew "prettier"
brew "fd"
brew "ripgrep"
brew "bat"
brew "jenv"
brew "pyenv"
brew "nvm"

tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"

cask "alfred"
cask "alacritty"
cask "karabiner-elements"
cask "kitty"
cask "bartender"
cask "xbar"

tap "koekeishiya/formulae"
brew "yabai"
brew "skhd"
tap FelixKratz/formulae
brew borders

