brew "autojump"
brew "fzf"
brew "git"
brew "htop"
brew "make"
brew "neovim", args: ["HEAD"]
brew "tmux"
brew "zsh"
brew "tig"
brew "jq"
brew "prettier"
brew "fd"
brew "ripgrep"
brew "bat"
brew "jenv"
brew "pyenv"
brew "nvm"

cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"

cask "alfred@4"
cask "karabiner-elements"
cask "kitty"
cask "bartender"
cask "xbar"
cask "bitwarden"
cask "shortcat"
cask "cleanshot"
cask "firefox"
cask "grammarly-desktop"
cask "spotify"
cask "chatgpt"
cask "alt-tab"
cask "obsidian"

tap "koekeishiya/formulae"
brew "yabai"
brew "skhd"
#brew tap FelixKratz/formulae
#brew borders

at_exit do 
  system "/opt/homebrew/bin/skhd --start-service"
  system "/opt/homebrew/bin/yabai --start-service"
end
