map alt+down neighboring_window down
map alt+right neighboring_window right
map alt+left neighboring_window left
map alt+up neighboring_window up
map ctrl+a>b>m close_other_windows_in_tab
map ctrl+a>r load_config_file
map ctrl+a>l clear_terminal to_cursor active
map ctrl+a>t new_tab
map ctrl+a>x close_tab
map super+enter launch --cwd=current
map ctrl+- resize_window wider
map ctrl+a>| launch --cwd=current --location=vsplit
map ctrl+a>- launch --cwd=current --location=hsplit
