#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      1.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config debug_output                 on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12
# yabai -m config external_bar all:32:0

yabai -m rule --add app!='^Google Chrome|Alacritty|kitty|zoom.us|IntelliJ IDEA$' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Project Structure|Preferences|Licenses|Data Sources and Drivers|Export Data|Pull to .*' manage=off
yabai -m rule --add app='Google Chrome' title='about:blank.*' manage=off layer=above
yabai -m rule --add app='Spotify' manage=off layer=above grid=1:3:0:0:2:1

echo "yabai configuration loaded.."

